apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pfa_complet_final-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: BROWSER
              value: "none"
            - name: REACT_APP_AUTH_URL
              value: "http://localhost:8081"
            - name: REACT_APP_BOOKING_URL
              value: "http://localhost:8082"
            - name: REACT_APP_NOTIFICATION_URL
              value: "http://localhost:8083"
            - name: REACT_APP_PAYMENT_URL
              value: "http://localhost:8084"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 3001
      targetPort: 3000