apiVersion: v1
kind: Secret
metadata:
  name: pfa-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  JWT_SECRET: "my-super-secret-key-for-pfa-application-2026"
